services:
  - type: worker
    name: spotigram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    # Render pulls environment variables directly from their web dashboard,
    # so we don't hardcode API keys here!